@URL=http://192.168.1.100/
@TOKEN =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzg4NTQ5MjAsImV4cCI6MTU3ODk0MTMyMCwiZGF0YSI6eyJJRCI6IjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiYWRtaW5AdHVyZXB1ZXN0by5jb20iLCJwYXNzIjoiOVlLcjNSS3FPRlRYQXhiTlhEazVQLiIsImRvYyI6IjAwMDAwMDAwIiwiZG9jdHlwZSI6IkMiLCJuYWMiOiJWIiwibmFtZSI6IkFkbWluIiwibGFzdCI6IlN5c3RlbSIsImxldmVsIjoiNSIsInBob25lIjoiMDAwMDAwMDAwMDEiLCJiaXJ0aCI6IjAwMDAtMDAtMDAiLCJjcmVhdGVkIjoiMjAxOS0wNy0xOSAwNDowMzowMyIsImFjdGl2ZSI6IjEiLCJ2ZXJpZmllZCI6IjEiLCJsb2dpbl9jb3VudCI6IjEwMCIsImlwIjoiMjEzMDcwNjQzMyIsImNvbmZpZyI6bnVsbCwidGhlbWUiOiIxIiwidXNlcnNfYmFuX3N0YXJ0IjpudWxsLCJ1c2Vyc19iYW5fZW5kIjpudWxsLCJ1c2Vyc19iYW5fZGV0YWlscyI6bnVsbH19.sUtlltS0gRn6DkjqBa3TjnJatZtORzxIIHBfq35N7P0
@FORMAT=?format=json

### Car Sub Parts Edit
GET {{URL}}/location{{FORMAT}}


###
POST {{URL}}/location{{FORMAT}}
Authorization: {{TOKEN}}
