@URL=http://192.168.1.100/
@TOKEN =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzI0NTIwODEsImV4cCI6MTU3MjUzODQ4MSwiZGF0YSI6eyJJRCI6IjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiYWRtaW5AdHVyZXB1ZXN0by5jb20iLCJwYXNzIjoiOVlLcjNSS3FPRlRYQXhiTlhEazVQLiIsImRvYyI6IjAwMDAwMDAwIiwiZG9jdHlwZSI6IkMiLCJuYWMiOiJWIiwibmFtZSI6IkFkbWluIiwibGFzdCI6IlN5c3RlbSIsImxldmVsIjoiNSIsInBob25lIjoiMDAwMDAwMDAwMDEiLCJiaXJ0aCI6IjAwMDAtMDAtMDAiLCJjcmVhdGVkIjoiMjAxOS0wNy0xOSAwNDowMzowMyIsImFjdGl2ZSI6IjEiLCJ2ZXJpZmllZCI6IjEiLCJsb2dpbl9jb3VudCI6IjI1IiwiaXAiOiIxOTIxNjgiLCJjb25maWciOm51bGwsInRoZW1lIjoiMSIsInVzZXJzX2Jhbl9zdGFydCI6bnVsbCwidXNlcnNfYmFuX2VuZCI6bnVsbCwidXNlcnNfYmFuX2RldGFpbHMiOm51bGx9fQ.VRz6VKRmPbL9on0gBLz6Pn-wRrUW9YlE3zkB_khITpc
@FORMAT=?format=json

### Car Sub Parts Edit
GET {{URL}}/location{{FORMAT}}


###
POST {{URL}}/location{{FORMAT}}
Authorization: {{TOKEN}}