@URL = http://api.carparts/
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY2MDUyMjEsImV4cCI6MTU3NjY5MTYyMSwiZGF0YSI6eyJJRCI6IjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiYWRtaW5AdHVyZXB1ZXN0by5jb20iLCJwYXNzIjoiOVlLcjNSS3FPRlRYQXhiTlhEazVQLiIsImRvYyI6IjAwMDAwMDAwIiwiZG9jdHlwZSI6IkMiLCJuYWMiOiJWIiwibmFtZSI6IkFkbWluIiwibGFzdCI6IlN5c3RlbSIsImxldmVsIjoiNSIsInBob25lIjoiMDAwMDAwMDAwMDEiLCJiaXJ0aCI6IjAwMDAtMDAtMDAiLCJjcmVhdGVkIjoiMjAxOS0wNy0xOSAwNDowMzowMyIsImFjdGl2ZSI6IjEiLCJ2ZXJpZmllZCI6IjEiLCJsb2dpbl9jb3VudCI6IjkwIiwiaXAiOiItMTA2MjczMTQyMCIsImNvbmZpZyI6bnVsbCwidGhlbWUiOiIxIiwidXNlcnNfYmFuX3N0YXJ0IjpudWxsLCJ1c2Vyc19iYW5fZW5kIjpudWxsLCJ1c2Vyc19iYW5fZGV0YWlscyI6bnVsbH19.3Ppt-NYzmYhArmMrEkYjhSZdWdMoyPe4cKwfyoZ2NLs
@FORMAT = ?format=json

###
POST {{URL}}notifications
Authorization: {{TOKEN}}